### PR TITLE
Show notifications when outside repo, fix tcsh case (fixes #64)

### LINKED ISSUE #64: Unable to recognize workspace
I get "... is outside any known perforce workspace" for a valid workspace. Please tell me what details I need to dig out.

### PR DESCRIPTION
**Pull request by artagnon**
It took me a while to get around to doing this, but atom-perforce reads the environment as promised: we just have to create a case for tcsh.

### CODE REVIEW

File: lib/environment.js [hunk 1]
```diff
@@ -20,6 +20,9 @@ if(os.platform() !== 'win32') {
     else if(/bash$/.test(shell)) {
         envCommands = ['~/.profile', '~/.bash_profile', '~/.bashrc'].map(getSourceShellEnvCommand);
     }
+    else if(/tcsh$/.test(shell)) {
+	envCommands = [shell + ' -c setenv'];
```
Comment (mattsawyer77) [inline lib/environment.js]: please fix the indentation, if you don't mind.

**Comment by artagnon** [comment]
Fixed, sorry about the sloppiness.
